### ISSUE TITLE
Set up TravisCI testing

### ISSUE THREAD

**Issue by ccadar** [klee/klee-uclibc#10]
We should simply copy those TravisCI targets from KLEE that enable uclibc.

**Comment by andreamattavelli** [comment]
@ccadar I might give it a try. I think it does not make sense to test too many targets.
I would thus restrict to:

- STP:Z3 + CMake + LLVM 3.4
- STP:Z3 + Autoconf + LLVM 2.9
- STP:Z3 + Autoconf + LLVM 3.4

Everything else I believe is irrelevant w.r.t. uclibc. Any thoughts @delcypher?

**Comment by delcypher** [comment]
In principle those targets are okay although I'd argue we shouldn't even be building KLEE. This repo is just klee-uclibc and thus we could just test building klee-uclibc. 

It looks like with a bit of work we could setup Travis builds of klee-uclibc to trigger rebuilds of KLEE's travis builds ([see here](https://docs.travis-ci.com/user/triggering-builds/)).

**Comment by andreamattavelli** [comment]
@delcypher I thought the same at the beginning, but then I realized what @ccadar probably meant: We have to check that the uclibc successfully builds, but also that its integration and use in KLEE is not disrupted.

**Comment by andreamattavelli** [comment]
@ccadar I have a draft of the Travis-CI script, but you need to enable Travis-CI integration first.

**Comment by ccadar** [comment]
Thanks, @andreamattavelli , it is now enabled.

**Comment by andreamattavelli** [comment]
@ccadar 
> Thanks, @andreamattavelli , it is now enabled.

Is it possible to provide us full access to Travis? I can't stop/start/restart jobs..

**Comment by ccadar** [comment]
You should now have access.  Closing this, as it's fixed by #11
