### ISSUE TITLE
OS X: ./configure -l report Kernel header files not found

### ISSUE THREAD

**Issue by hailinzeng** [klee/klee-uclibc#15]
Hi, I'm trying to compile klee on macOS 10.12.6 (kernel version Darwin 16.7.0).  llvm, stp and minisat are success compiled. Now I'm stuck in compile uclibc.

./configure -l
INFO:Disabling assertions
INFO:Configuring for Debug build
INFO:Configuring for LLVM bitcode archive
INFO:Using llvm-config at.../usr/local/opt/llvm/bin/llvm-config
INFO:Using llvm tool dir.../usr/local/Cellar/llvm/5.0.0/bin
INFO:Found "/usr/local/Cellar/llvm/5.0.0/bin/llvm-objdump".
INFO:Found "/usr/local/Cellar/llvm/5.0.0/bin/llvm-link".
INFO:Found "/usr/local/Cellar/llvm/5.0.0/bin/llvm-ar".
INFO:Found "/usr/local/Cellar/llvm/5.0.0/bin/llvm-nm".
INFO:Searching for LLVM Bitcode compiler...
INFO:Found clang in LLVM Build dir.../usr/local/Cellar/llvm/5.0.0/bin/clang
INFO:Testing LLVM Bitcode compiler.../usr/local/Cellar/llvm/5.0.0/bin/clang
INFO:Compiler /usr/local/Cellar/llvm/5.0.0/bin/clang works
INFO:Using LLVM Bitcode Compiler.../usr/local/Cellar/llvm/5.0.0/bin/clang
INFO:Checking for ncurses...
INFO:Writing templated file to "/Users/apple/Documents/Dev/klee-uclibc/Makefile.klee"
INFO:Setting up pre-made configure for...x86_64
INFO:Installing .config file
INFO:Looking for kernel include path...
ERROR:Kernel header files not found at '/usr/include': '/usr/include/asm/unistd.h' is absent.Export the UCLIBC_KERNEL_HEADERS environment variable to change thedefault path ('/usr/include')

**Comment by ccadar** [comment]
Unfortunately, uclibc does not work on macOS.  You can still use KLEE's more limited 
internal libc (`--libc=klee`), or try to link another libc.

**Comment by skull-squadron** [comment]
[musl](https://www.musl-libc.org/) is fairly portable IIRC
