### ISSUE TITLE
Test and then announce new klee-uclibc

### ISSUE THREAD

**Issue by delcypher** [klee/klee-uclibc#2]
I have pushed three new branches
- klee_legacy_x86_64 : Legacy klee-uclibc for 64-bit, this will **not** be maintained
- klee_legacy_i686 : Legacy klee-uclibc for 32-bit, this will **not** be maintained
- klee_0_9_29 : This is the new klee-uclibc

klee_0_9_29 : Is the built on top of the 0_9_29 branch (not the same as the 0_9_29 tag). I have selectively applied changes from the original klee-uclibc as several commits and have I tried my best to provide good commit messages. I found this quite challenging and it's lead me to conclude that we **really** need to rethink how KLEE and uclibc should interact because some of this code is horrible.

Building klee-uclibc on this branch succeeds for
- llvm-gcc4.2 (llvm2.9) 32-bit and 64-bit
- clang 3.3 32-bit and 64bit (Thanks to @MartinNowack )

This branch on 64-bit currently passes the KLEE tests when built with llvm-gcc, on 32-bit it doesn't quite pass but I need to look into this further. I don't believe this is related to uclibc because KLEE's test seem to be broken on 32-bit if I use the old klee-uclibc as well.

What I would like to do is (with permission from all contributors @ccadar @MartinNowack )
- Remove the old klee_monolithic and klee_monolithic_llvm33 branches and just continue development on the klee_0_9_29 branch. I don't want to do this too soon because there are some changes on klee_monolithic_llvm33 from @MartinNowack that are not on the klee_0_9_29 branch. Perhaps we should switch to a push-pull model for the klee_0_9_29 branch?
- Then make klee_0_9_29 the default branch for this repository.
- Then announce these changes on the klee-dev mailing list and update the "Getting Started" documentation for KLEE to instruct people to use klee-uclibc from this repository. The klee-uclibc tarballs on the KLEE website are broken (and have been for a while) so I don't see any good reason to delay doing this.

**Comment by MartinNowack** [comment]
In general, looks great!!

I checked with KLEE for 3.3 and added new pull request ccadar/klee#70. Beside that, no changes to the worse according to regression suite.

@delcypher I'm fine with your suggestions. Can you add a list of tests which are broken according to uclibc either here or ccadar/klee#44 if better suited?

Thanks a lot.

**Comment by ccadar** [comment]
Hi guys, it's great to see that the revised klee-uclibc is pretty much ready to go!

Despite that fact that this makes much easier now to compile and maintain, I think we should not require users to compile klee-uclibc, unless they need to change it.  In fact, I would like to move in the same direction with KLEE overall.

What I'd like to do is to provide precompiled LLVM archives (essentially the libc.a file) for various LLVM versions that we support. To keep this up-to-date, we could make use of KLEE's buildbot (at https://github.com/ccadar/klee-buildbot).  The only thing that needs to be done is to change the --with-uclibc option in KLEE to also accept an archive file as argument).  

Let me know if you have any comments.

**Comment by delcypher** [comment]
@ccadar I have already put forward my views on this to you person but I think I should repeat my view for the benefit of @MartinNowack and anyone else reading.

I would prefer to **not** instruct people building KLEE from source to use a pre-built klee-uclibc. I would much rather do the following:
- Provide packages for common distributions for KLEE which contains everything pre-built which users can easily download and install. These could be periodically built by a build-bot slave or something like the OpenSUSE build service.
- Provide building from source instructions that walk the user through building KLEE from scratch. These instructions would include building KLEE-uclibc from source.

One thing I think we could consider is making KLEE-uclibc a git submodule in the KLEE repository. Although you can swap out klee-uclibc versions at the moment if we fix KLEE-uclibc so it is not a massive hack we are going to need to change KLEE and so the KLEE revision will be specifically tied to certain versions of KLEE-uclibc. This information is captured by git submodules and would prevent users from using the wrong klee-uclibc version with KLEE.

**Comment by ccadar** [comment]
Hi @delcypher,  I agree it would be great to provide packages for common distributions for KLEE; but I think we are still far away from that goal.  However, I think anything that makes it easier for users to install KLEE would be welcome by the community.  As you know, many users struggle to install KLEE, or are put off from trying it by numerous dependencies that need to be compiled, and in particular LLVM, STP, and klee-uclibc.  The way I see it is that switching to an "apt-get install klee" model is non-trivial, and in any case there are no volunteers for the job.  On the other hand, it's easy to remove some of these dependencies, for example by distributing precompiled versions of klee-uclibc and STP.  Given that these components are pretty stable (and we can easily regenerate them in an automatic fashion), I don't see the advantage of forcing regular users (as opposed to developers) to recompile them.

**Comment by delcypher** [comment]
@ccadar Although creating KLEE packages for distributions is not completely trivial I don't think it's particularly difficult either.

I've made a [pull request](https://github.com/ccadar/klee/pull/78) in KLEE which allows `make install` to work correctly. As I see it, that fixes the major problems that would of prevented anyone from creating usable KLEE packages in the past.

I believe on Ubuntu launchpad it is possible to have PPAs so it should be straight forward to create a KLEE package. Although I have no experience creating Ubuntu/Debian packages.

**Comment by MartinNowack** [comment]
@delcypher With the packaging for Ubuntu/Debian I could help - I've done a few things already.
The biggest problem is a correctly running llvm toolchain. The rest is more the type of "piece of cake".

**Comment by ddcc** [comment]
Originally, we considered setting up a PPA for Debian/Ubuntu, but it required separate packages for STP, uClibc, and Klee. However, building Klee was relatively complex due to all the dependencies, and I wasn't familiar enough with PPA's to have the automated build process successfully locate all the dependencies.

Instead, when setting up the Buildbot, I configured it to generate pre-built archives for both the stable and unstable branches of Klee, STP, uClibc, and LLVM. These can be downloaded from http://vm-klee.doc.ic.ac.uk:55555/binaries.

At that time, I also worked on porting forward the changes to klee-uclibc from the original version of uClibc (don't remember the specific version), to 0.9.33.2 (the current stable). However, I didn't have the time to thoroughly test it, and don't believe it works correctly with klee. Nevertheless, it might be useful, and is at https://github.com/ddcc/klee-uclibc-0.9.33.2/commit/7f64095b29e921a9489ae46d1696255e561519f7.

**Comment by ccadar** [comment]
Hi @ddcc, regarding the executables: unfortunately, they don't work yet, as there are still some dependencies on hard-coded paths.  Currently, running the klee binary on any program triggers the following error:

klee: error: Cannot find linker input '/home/buildbot/slave/klee-stable/build/Release+Asserts/lib/libkleeRuntimeIntrinsic.bca'

**Comment by ddcc** [comment]
Yes, I recall that was one of the problems I encountered. I thought I had changed it to compile with a relative path, but it's been quite a while since I last touched it. Even with the correct klee-uclibc library though, the updated version of klee-uclibc 0.9.33.2 would fail some of the included testcases.

I haven't really looked through the changes that have been made to the klee source, but it's likely that the Buildbot script is out of date and might need to be changed to reflect the current build process, since even klee-stable seems to be failing.

**Comment by ccadar** [comment]
The buildbot failure is a separate issue, but yes, I need to investigate it (it's a recent failure,see the history at: http://vm-klee.doc.ic.ac.uk:55555/builders/klee-stable).  What we need to do is configure the buildbot to send an email to klee-commits@imperial.ac.uk when a failure in klee-stable occurs.  Would you like to do this?  Also, more documentation on the buildbot would be nice, right now people are afraid to touch it :)

**Comment by delcypher** [comment]
@ccadar The hard coded path issues is half fixed (I'm no going to fix it because the fix is "good enough" and proper portability is too complicated). If you install klee then the `klee` exectuable will look for the runtime libraries in the place they were installed. So you could do something like this

```
./configure --prefix=/opt/klee #other KLEE configure flags
make
mkdir dist/
make DESTDIR=`$pwd`/dist install
```

The contents of `$pwd/dist` can now be tar-balled up. If the tarball is extracted and placed in the correct location (i.e. the `klee` executable is located at `/opt/klee/bin/klee` and runtime libraries in `/opt/klee/lib/`) then KLEE will "just work".

**Comment by ddcc** [comment]
I'm not sure I'll have time to work on the Buildbot, at least in the next few weeks, but there's an online tutorial for Buildbot at http://docs.buildbot.net/current/tutorial/, and API documentation at http://docs.buildbot.net/latest/. The whole tool and its configuration scripts are written in Python, so it shouldn't be too hard to get started.

**Comment by ccadar** [comment]
@delcypher , is this old issue still relevant? I believe we can close it.

**Comment by delcypher** [comment]
Yes let's close this.
