### ISSUE TITLE
cannot generate aarch64 pre-made config files.

### ISSUE THREAD

**Issue by contr4l** [klee/klee-uclibc#28]
I am using an aarch64  machine to make klee-uclibc, and I found no supported pre-made config files in klee-premade-configs, 
README said I can run make menuconfig to generate config file, but I cannot find the aarch64 option in architecture.
I wonder if I can install this plugin in aarch64 env？

**Comment by MartinNowack** [comment]
@contr4l klee-uclibc is built on top of uclibc (`0.9.29`) which was released 2007. It was not supported that time.

**Comment by contr4l** [comment]
> @contr4l klee-uclibc is built on top of uclibc (`0.9.29`) which was released 2007. It was not supported that time.

if I still want to use posix-runtime in klee on aarch64 platform, what can I do? should I link my code to a dynamic .so file or static library?
I wonder if I can get a sample for using external reference "strcmp" : ).

**Comment by MartinNowack** [comment]
If you only need the `strcmp` function, you should KLEE's `--libc=klee` option to use the included libc implementation.

I'll close this issue for now. If there is anything missing, please re-open it.
