### ISSUE TITLE
Build with locale?

### ISSUE THREAD

**Issue by delcypher** [klee/klee-uclibc#3]
There is an inconsistency between klee_legagcy_i686 and klee_legacy_x86_64.
- klee_legacy_i686 was configured to build with locale (it included a locale tarball `extra/locale/uClibc-locale-030818.tgz`) 
- klee_legacy_x86_64 was not configured to build with locale.

Should we build klee_0_9_29 build with locale?

**Comment by ccadar** [comment]
Hi Dan, I think we should perhaps build with that locale tarball.

**Comment by MartinNowack** [comment]
@delcypher @ccadar We are now building with locale by default in `klee_0_9_29`.
