### ISSUE TITLE
www.uclibc.org not handled by Quad9 secure DNS

### ISSUE THREAD

**Issue by ricardaxel** [klee/klee-uclibc#49]
Hello, secured service of [Quad9 DNS](https://www.quad9.net/service/service-addresses-and-features) can't resolve www.uclibc.org link used in [this makefile](https://github.com/klee/klee-uclibc/blob/klee_0_9_29/extra/locale/Makefile.in#L159).

``` bash
# secured : Malware Blocking, DNSSEC Validation
>> nslookup www.uclibc.org 9.9.9.9
Server:         9.9.9.9
Address:        9.9.9.9#53

 ** server cant find www.uclibc.org: NXDOMAIN

# Unsecured: No Malware blocking, no DNSSEC validation
>> nslookup www.uclibc.org 9.9.9.10
Server:         9.9.9.10
Address:        9.9.9.10#53

Non-authoritative answer:
Name:   www.uclibc.org
Address: 140.211.167.122
```

To make sure we download a trusted version of locale data, could you maybe add the `uClibc-locale-030818.tgz` file to this repo ? Thanks !

**Comment by ccadar** [comment]
@ricardaxel thanks for reporting this.  Could you open a PR?
