### ISSUE TITLE
#include_next <limits.h> missing

### ISSUE THREAD

**Issue by msoos** [klee/klee-uclibc#7]
While compiling on Ubuntu 12.04-03 LTS having gcc 4.6.3, having llvm-2.9 and clang 2.9:

```
$ clang --version
clang version 2.9 (tags/RELEASE_29/final)
Target: x86_64-unknown-linux-gnu
Thread model: posix
```

I get the error during `make`:

```
*
* uClibc development/debugging options
*
Cross-compiling toolchain prefix (CROSS_COMPILER_PREFIX) [] 
Enter any extra CFLAGS to use to build uClibc (UCLIBC_EXTRA_CFLAGS) [] 
Build uClibc with debugging symbols (DODEBUG) [N/y/?] n
Strip libraries and executables (DOSTRIP) [N/y/?] n
Build uClibc with run-time assertion testing (DOASSERTS) [N/y/?] n
Build malloc with debugging support (UCLIBC_MALLOC_DEBUGGING) [N/y/?] n
Compiler Warnings (WARNINGS) [-Wall] -Wall
Enable extra annoying warnings (EXTRA_WARNINGS) [N/y/?] n
Compile all sources at once into an object (DOMULTI) [N/y/?] n
Manuel's hidden warnings (UCLIBC_MJN3_ONLY) [N/y/?] n
#
# configuration written to .config
#
./extra/scripts/conf-header.sh .config > include/bits/uClibc_config.h
  CC libcrypt/des.os
clang: warning: argument unused during compilation: '-fgnu89-inline'
In file included from libcrypt/des.c:62:
In file included from ./include/sys/param.h:22:
In file included from ./include/limits.h:124:
/usr/include/limits.h:125:16: fatal error: 'limits.h' file not found
# include_next <limits.h>
               ^
1 error generated.
make: *** [libcrypt/des.os] Error 1
```

I configured as per http://ccadar.github.io/klee/GetStarted.html :

```
./configure --make-llvm-lib
```

And guess why I'm getting this error?

**Comment by delcypher** [comment]
I checked on an Ubuntu 12.04-03 LTS machine and the header file you are missing is supplied by the `libc6-dev` package. Please make sure it's installed.

If that doesn't work then I'm not sure what's wrong, I only ever tested with llvm-gcc 4.2 and clang 3.3 and it works fine for those scenarios.

**Comment by msoos** [comment]
I re-installed `libc6-dev` and it still complains. Anyway, I compiled llvm-gcc, and gave `./configure --with-cc /usr/local/bin/gcc --make-llvm-lib`, which compiled without any issues. Weird stuff. Closing, as this can be avoided with llvm-gcc.

**Comment by msoos** [comment]
Thanks for the really quick feedback! I'll try my best to post a VM that has all the stuff (llvm, klee, klee-uclbc, etc.) installed & compiled, etc. so the startup time for others will be easier.

**Comment by delcypher** [comment]
Thanks. 

I actually just realise I mis-read your error message which actually says that `/usr/include/limits.h` does exist on your system but it has a problem using then including it again. But I'm glad you solved it.

I think it's [this issue](http://lists.cs.uiuc.edu/pipermail/llvmbugs/2010-February/010649.html)

**Comment by MartinNowack** [comment]
Just as a small addition, Clang's 2.9 searcher for include files was quite broken on the one hand. On the other hand, with Ubuntu 12.04 they introduced multilib support, i386 and 64bit headers are in different locations. The issue is clang - they fixed it with newer versions (but still you have to add each new ubuntu version to clang code). So it's not necessarily forward compatible.
